### ISSUE TITLE
Is this a web-based Taskbook? Should that be referenced?

### ISSUE THREAD

**Issue by karlbright** [huytd/pomoday-v2#1]
First of all, i'm happy to see this love and usable because i've been meaning to build something similar for awhile but time always got away from me. I've used [taskbook](https://github.com/klaussinani/taskbook) via the command line currently but that just doesn't tie nicely into my workflow as well as using it via browser does.

Which leads me to my question - Is this primarily based off of Taskbook? The interface and functionality looks like it matches quite closely to that program.

While it's completely fine that it is, I think it would be great to give a shoutout and point people to that if they wish to use a command line alternative. If not, then there it's almost definitely worth a look at. I'm tempted to look at trying to hook that up to point to Pomodoro as long as those endpoints are easily accessible.

Great work so far and keep it up!

**Comment by huytd** [comment]
Hi, thank you so much for the feedback!

Yes, this app is heavily inspired by taskbook, I'll add it to the Readme.

I also used Taskbook a lot but frustrated in some way because it's lack of the things I need, like the persistent UI, an actual time tracking, which led me to build this app. The reason I built it as a web app is to make it usable across devices (still WIP btw).

**Comment by karlbright** [comment]
@huytd Awesome. I figured as much given how it looks and how the interactions felt. Giving it a whirl to see if it fixes my issue with Taskbook too. Thanks for the reply. :+1:
